import Head from 'next/head';

export function PageHead() {
  return (
    <Head>
      <title>Zerf - Kickkoff</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
